"""
Unit tests for the tenant2fast Alembic chains (work unit 1.6, alembic-2fast
change).

No PostgreSQL and no database are required:

1. Both chain shims (``migrations/tenant2fast-auth/env.py`` and
   ``migrations/tenant2fast-rbac/env.py``) exist and dispatch to the shared
   async env shipped by ``pgsqlasync2fast_fastapi.migrations``.
2. Importing ``tenant2fast_fastapi`` registers ``tenant2fast-auth`` under the
   ``"auth"`` lane (after the oauth and permissions-global chains once those
   releases are published) and ``tenant2fast-rbac`` under the ``"tenant"``
   lane, with the exact shipping contract (package, script path, version
   table, owned tables).
3. The autogenerated baselines ``0001_initial`` are parseable via
   ``ScriptDirectory`` (zero DB); each owns exactly its lane's tables and no
   foreign table is proposed (design D9 ownership filter).
4. Both chains render to SQL in alembic OFFLINE mode through the shared env
   (shim dispatch -> offline configure with literal_binds).

Run with: uv run --all-groups pytest tests/test_migration_chains.py -v
"""

from __future__ import annotations

import os
from importlib import resources

os.environ.setdefault("SECRET_KEY", "test-secret-key-not-for-production")
# The repo's conftest forces DB_CONNECTIONS__AUTH__IS_SUPERUSER=true, which
# requires the remaining auth connection fields when the settings import
# chain runs (oauth2fast -> pgsqlasync2fast). These setdefaults mirror the
# .env contract so the import chain can load in CI-less environments.
os.environ.setdefault("DB_CONNECTIONS__AUTH__HOST", "localhost")
os.environ.setdefault("DB_CONNECTIONS__AUTH__USERNAME", "test")
os.environ.setdefault("DB_CONNECTIONS__AUTH__PASSWORD", "test")
os.environ.setdefault("DB_CONNECTIONS__AUTH__DATABASE", "test")

from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from pgsqlasync2fast_fastapi import get_lane_chains

import tenant2fast_fastapi  # noqa: F401  (side effect: registers the chains)

AUTH_SCRIPT_LOCATION = "tenant2fast_fastapi:migrations/tenant2fast-auth"
RBAC_SCRIPT_LOCATION = "tenant2fast_fastapi:migrations/tenant2fast-rbac"


def _auth_spec():
    chains = [
        c
        for c in get_lane_chains("auth")
        if c.package == "tenant2fast_fastapi"
    ]
    assert len(chains) == 1, (
        f"expected exactly one tenant2fast auth chain, got {len(chains)}"
    )
    return chains[0]


def _rbac_spec():
    chains = get_lane_chains("tenant")
    assert len(chains) == 1, (
        f"expected exactly one tenant lane chain, got {len(chains)}"
    )
    return chains[0]


def test_chain_shims_exist_and_dispatch_to_shared_env():
    for chain_dir in ("tenant2fast-auth", "tenant2fast-rbac"):
        shim = (
            resources.files("tenant2fast_fastapi")
            / "migrations"
            / chain_dir
            / "env.py"
        )
        assert shim.is_file(), f"missing shim for {chain_dir}"
        text = shim.read_text()
        assert "pgsqlasync2fast_fastapi.migrations" in text
        assert "run_migrations_offline" in text
        assert "run_migrations_online" in text
        assert "context.is_offline_mode()" in text


def test_tenant_auth_chain_registered_in_auth_lane_with_contract():
    spec = _auth_spec()
    assert spec.package == "tenant2fast_fastapi"
    assert spec.script_path == "migrations/tenant2fast-auth"
    assert spec.version_table == "alembic_version_tenant_auth"
    assert spec.owned_tables == frozenset({"tenants", "tenant_users"})


def test_tenant_rbac_chain_registered_in_tenant_lane_with_contract():
    spec = _rbac_spec()
    assert spec.package == "tenant2fast_fastapi"
    assert spec.script_path == "migrations/tenant2fast-rbac"
    assert spec.version_table == "alembic_version_tenant_rbac"
    # Design D9: at registration time the tenant chain owns exactly the nine
    # package tables (complete tenant_metadata partition), disjoint from the
    # auth chain's tables. Other test/consumer models may join the live
    # metadata later, so the owned_tables snapshot is compared against the
    # registration-time partition (and stays a subset of the live metadata),
    # not against the metadata table set at assertion time.
    assert spec.owned_tables == frozenset(
        {
            "categories",
            "roles",
            "routes",
            "users",
            "permissions",
            "role_users",
            "permission_roles",
            "permission_routes",
            "permission_users",
        }
    )
    assert spec.owned_tables.isdisjoint(_auth_spec().owned_tables)
    assert spec.owned_tables <= frozenset(spec.target_metadata.tables)


def test_tenant_auth_chain_is_last_in_auth_lane():
    # FK-proven order (design D6): oauth -> permissions-global ->
    # tenant2fast-auth. The tenant2fast auth chain may never run before its
    # auth-lane predecessors, so it must sit at the end of the lane.
    chains = get_lane_chains("auth")
    assert chains
    auth_spec_idx = next(
        i
        for i, c in enumerate(chains)
        if c.package == "tenant2fast_fastapi"
    )
    assert auth_spec_idx == len(chains) - 1
    assert chains[auth_spec_idx].script_path == "migrations/tenant2fast-auth"


def test_tenant_auth_target_metadata_holds_owned_tables():
    spec = _auth_spec()
    for table in ("tenants", "tenant_users"):
        assert table in spec.target_metadata.tables


def test_auth_baseline_0001_parseable_and_owns_tenants_only():
    cfg = Config()
    cfg.set_main_option("script_location", AUTH_SCRIPT_LOCATION)
    script = ScriptDirectory.from_config(cfg)

    head = script.get_current_head()
    assert head == "0001"
    rev = script.get_revision(head)
    assert rev.down_revision is None  # single-baseline chain
    assert rev.path.endswith("0001_initial.py"), rev.path

    with open(rev.path) as fh:
        text = fh.read()
    # Alembic renders third-party types module-qualified without importing the
    # module (alembic 1.20.0 _repr_type); the baseline must carry the import.
    assert "import sqlmodel" in text
    for table in ("tenants", "tenant_users"):
        assert f"op.create_table('{table}'" in text
    # Ownership (design D9): no foreign table may be proposed by this chain.
    for foreign in (
        "users",
        "roles",
        "permissions",
        "permission_categories",
        "routes",
        "role_users",
        "permission_assignments",
        "permission_routes",
    ):
        assert f"op.create_table('{foreign}'" not in text


def test_rbac_baseline_0001_parseable_and_owns_all_tenant_tables():
    cfg = Config()
    cfg.set_main_option("script_location", RBAC_SCRIPT_LOCATION)
    script = ScriptDirectory.from_config(cfg)

    head = script.get_current_head()
    assert head == "0001"
    rev = script.get_revision(head)
    assert rev.down_revision is None  # single-baseline chain
    assert rev.path.endswith("0001_initial.py"), rev.path

    with open(rev.path) as fh:
        text = fh.read()
    assert "import sqlmodel" in text
    for table in sorted(_rbac_spec().owned_tables):
        assert f"op.create_table('{table}'" in text
    # Ownership: the auth-lane tables must not be proposed by the tenant chain.
    for foreign in ("tenants", "tenant_users"):
        assert f"op.create_table('{foreign}'" not in text


def _offline_render(location: str, version_table: str, spec) -> None:
    # Executes the chain shim -> shared runner env offline path: the whole
    # chain (env + versions) renders SQL without any database. Proves the
    # shim imports resolve and the baseline is loadable by alembic.
    cfg = Config()
    cfg.set_main_option("script_location", location)
    cfg.set_main_option(
        "sqlalchemy.url", "postgresql+asyncpg://u:p@h:5432/db"
    )
    cfg.set_main_option("version_table", version_table)
    cfg.attributes["target_metadata"] = spec.target_metadata

    command.upgrade(cfg, "head", sql=True)


def test_auth_chain_upgrades_to_head_in_offline_mode():
    _offline_render(
        AUTH_SCRIPT_LOCATION, "alembic_version_tenant_auth", _auth_spec()
    )


def test_rbac_chain_upgrades_to_head_in_offline_mode():
    _offline_render(
        RBAC_SCRIPT_LOCATION, "alembic_version_tenant_rbac", _rbac_spec()
    )