"""initial

Revision ID: 0001
Revises: 
Create Date: 2026-09-17 08:06:02.883742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_created_by'), 'categories', ['created_by'], unique=False)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_index(op.f('ix_categories_updated_by'), 'categories', ['updated_by'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_created_by'), 'roles', ['created_by'], unique=False)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_index(op.f('ix_roles_updated_by'), 'roles', ['updated_by'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_created_by'), 'routes', ['created_by'], unique=False)
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.create_index(op.f('ix_routes_method'), 'routes', ['method'], unique=False)
    op.create_index(op.f('ix_routes_path'), 'routes', ['path'], unique=False)
    op.create_index(op.f('ix_routes_updated_by'), 'routes', ['updated_by'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('auth_user_id', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('department', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_auth_user_id'), 'users', ['auth_user_id'], unique=True)
    op.create_index(op.f('ix_users_created_by'), 'users', ['created_by'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_updated_by'), 'users', ['updated_by'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('permission_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_created_by'), 'permissions', ['created_by'], unique=False)
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_index(op.f('ix_permissions_permission_category_id'), 'permissions', ['permission_category_id'], unique=False)
    op.create_index(op.f('ix_permissions_updated_by'), 'permissions', ['updated_by'], unique=False)
    op.create_table('role_users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_users_created_by'), 'role_users', ['created_by'], unique=False)
    op.create_index(op.f('ix_role_users_id'), 'role_users', ['id'], unique=False)
    op.create_index(op.f('ix_role_users_role_id'), 'role_users', ['role_id'], unique=False)
    op.create_index(op.f('ix_role_users_updated_by'), 'role_users', ['updated_by'], unique=False)
    op.create_index(op.f('ix_role_users_user_id'), 'role_users', ['user_id'], unique=False)
    op.create_table('permission_roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_permission_roles_role_permission')
    )
    op.create_index(op.f('ix_permission_roles_created_by'), 'permission_roles', ['created_by'], unique=False)
    op.create_index(op.f('ix_permission_roles_id'), 'permission_roles', ['id'], unique=False)
    op.create_index(op.f('ix_permission_roles_permission_id'), 'permission_roles', ['permission_id'], unique=False)
    op.create_index(op.f('ix_permission_roles_role_id'), 'permission_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_permission_roles_updated_by'), 'permission_roles', ['updated_by'], unique=False)
    op.create_table('permission_routes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_routes_created_by'), 'permission_routes', ['created_by'], unique=False)
    op.create_index(op.f('ix_permission_routes_id'), 'permission_routes', ['id'], unique=False)
    op.create_index(op.f('ix_permission_routes_permission_id'), 'permission_routes', ['permission_id'], unique=False)
    op.create_index(op.f('ix_permission_routes_route_id'), 'permission_routes', ['route_id'], unique=False)
    op.create_index(op.f('ix_permission_routes_updated_by'), 'permission_routes', ['updated_by'], unique=False)
    op.create_table('permission_users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('is_allowed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_users_created_by'), 'permission_users', ['created_by'], unique=False)
    op.create_index(op.f('ix_permission_users_id'), 'permission_users', ['id'], unique=False)
    op.create_index(op.f('ix_permission_users_permission_id'), 'permission_users', ['permission_id'], unique=False)
    op.create_index(op.f('ix_permission_users_updated_by'), 'permission_users', ['updated_by'], unique=False)
    op.create_index(op.f('ix_permission_users_user_id'), 'permission_users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permission_users_user_id'), table_name='permission_users')
    op.drop_index(op.f('ix_permission_users_updated_by'), table_name='permission_users')
    op.drop_index(op.f('ix_permission_users_permission_id'), table_name='permission_users')
    op.drop_index(op.f('ix_permission_users_id'), table_name='permission_users')
    op.drop_index(op.f('ix_permission_users_created_by'), table_name='permission_users')
    op.drop_table('permission_users')
    op.drop_index(op.f('ix_permission_routes_updated_by'), table_name='permission_routes')
    op.drop_index(op.f('ix_permission_routes_route_id'), table_name='permission_routes')
    op.drop_index(op.f('ix_permission_routes_permission_id'), table_name='permission_routes')
    op.drop_index(op.f('ix_permission_routes_id'), table_name='permission_routes')
    op.drop_index(op.f('ix_permission_routes_created_by'), table_name='permission_routes')
    op.drop_table('permission_routes')
    op.drop_index(op.f('ix_permission_roles_updated_by'), table_name='permission_roles')
    op.drop_index(op.f('ix_permission_roles_role_id'), table_name='permission_roles')
    op.drop_index(op.f('ix_permission_roles_permission_id'), table_name='permission_roles')
    op.drop_index(op.f('ix_permission_roles_id'), table_name='permission_roles')
    op.drop_index(op.f('ix_permission_roles_created_by'), table_name='permission_roles')
    op.drop_table('permission_roles')
    op.drop_index(op.f('ix_role_users_user_id'), table_name='role_users')
    op.drop_index(op.f('ix_role_users_updated_by'), table_name='role_users')
    op.drop_index(op.f('ix_role_users_role_id'), table_name='role_users')
    op.drop_index(op.f('ix_role_users_id'), table_name='role_users')
    op.drop_index(op.f('ix_role_users_created_by'), table_name='role_users')
    op.drop_table('role_users')
    op.drop_index(op.f('ix_permissions_updated_by'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_permission_category_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_created_by'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_users_updated_by'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_created_by'), table_name='users')
    op.drop_index(op.f('ix_users_auth_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_routes_updated_by'), table_name='routes')
    op.drop_index(op.f('ix_routes_path'), table_name='routes')
    op.drop_index(op.f('ix_routes_method'), table_name='routes')
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_created_by'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_roles_updated_by'), table_name='roles')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_created_by'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_categories_updated_by'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_created_by'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
